server:
  port: 8080

spring:
  application:
    name: hello
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    id-type: 0 #id自增
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl